version: "3"
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    redisinsight:
        image: redislabs/redisinsight
        ports:
            - 8001:8001
        depends_on:
            - redis
        volumes:
            - redisinsight_db:/db

    nginx:
      build:
        context: ./nginx
      depends_on:
        - transaction-log_1
        - transaction-log_2
        - transaction-log_3
      ports:
        - "8000:80"
    
    transaction-log_1:
      build: .
      command: "uvicorn app.app:app --host=0.0.0.0"
      depends_on:
          - redis
      ports:
          - "8081:8000"

    transaction-log_2:
      build: .
      command: "uvicorn app.app:app --host=0.0.0.0"
      depends_on:
          - redis
      ports:
          - "8082:8000"
    
    transaction-log_3:
      build: .
      command: "uvicorn app.app:app --host=0.0.0.0"
      depends_on:
          - redis
      ports:
          - "8083:8000"

    prometheus:
      image: prom/prometheus:v2.30.3
      volumes:
        - ./prometheus/:/etc/prometheus/
      ports:
        - 9090:9090

volumes:
    redis_data:
    redisinsight_db:
